### ISSUE TITLE
[Question] Is it possible to create custom CDA datasources ?

### ISSUE THREAD

**Issue by kleysonr** [webdetails/cda#340]
I would like to know if it's possible to create a custom CDA datasource.

I've been playing with a beanshell datasource (scriptable over scripting) to call a custom java class that allow me to query a MongoDB (https://github.com/kleysonr/pentaho-cda-mongodb) and a GraphQL server (https://github.com/kleysonr/pentaho-cda-graphql).

For many reasons I would like to avoid writing java code as a beanshell.

Best Regards.
Kleyson Rios.

**Comment by pamval** [comment]
Creating custom data source involves changing CDA. It's not possible to do so by adding a plugin or something.

Here's an example of what had to be done to add the dataservices datasource a couple of years ago:

https://github.com/webdetails/cda/commit/82ca2298980f968209f316f1fb02e5e74bbe844f
